### ISSUE TITLE
When I try to run main.py, I got the error "only integer scalar arrays can be converted to a scalar index"

### ISSUE THREAD

**Issue by modanesh** [AlexOuyang/RealTimeFacialRecognition#1]
I have python2.7 and numpy1.8. When I want to run main.py, I got the error:

```
Traceback (most recent call last):
  File "/Users/Mohamad/Desktop/RealTimeFaceRecognition-master/scripts/main.py", line 160, in <module>
    name_to_display = svm.predict(clf, pca, face_to_predict, face_profile_names)
  File "/Users/Mohamad/Desktop/RealTimeFaceRecognition-master/scripts/svm.py", line 306, in predict
    name = face_profile_names[pred][0]
TypeError: only integer scalar arrays can be converted to a scalar index

```

Anyone knows what's the problem?

**Comment by saiparvathi** [comment]
In scripts/svm.py 
just replace line
    name = face_profile_names[pred][0] 
as
    name = face_profile_names[pred[0]]

**Comment by veeraharin** [comment]
thank you its works awesome
