### ISSUE TITLE
ValueError: Expected 2D array, got 1D array instead:

### ISSUE THREAD

**Issue by esakkirajan123** [AlexOuyang/RealTimeFacialRecognition#6]
Traceback (most recent call last):
  File "C:\Users\RAJA\Desktop\Opencv\RealTimeFaceRecognition-master\RealTimeFaceRecognition-master\scripts\main.py", line 158, in <module>
    name_to_display = svm.predict(clf, pca, face_to_predict, face_profile_names)
  File "C:\Users\RAJA\Desktop\Opencv\RealTimeFaceRecognition-master\RealTimeFaceRecognition-master\scripts\svm.py", line 308, in predict
    principle_components = pca.transform(img)
  File "C:\Python27\lib\site-packages\sklearn\decomposition\pca.py", line 757, in transform
    X = check_array(X)
  File "C:\Python27\lib\site-packages\sklearn\utils\validation.py", line 441, in check_array
    "if it contains a single sample.".format(array))
ValueError: Expected 2D array, got 1D array instead:
array=[ 0  0  0 ... 47 49 49].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

Please help me out from this.

Thanks

**Comment by abdghazi** [comment]
hey man 
have you been able to solve this ?

**Comment by ubihacks** [comment]
Hey man!
Did You Got any solution For That
